// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgD7L2p3y2bw9nvOj_H46X7EBJLZMw_lI',
    appId: '1:891579140465:web:dummy_web_app_id',
    messagingSenderId: '891579140465',
    projectId: 'smarthomeautomation-3d999',
    authDomain: 'smarthomeautomation-3d999.firebaseapp.com',
    databaseURL: 'https://smarthomeautomation-3d999-default-rtdb.firebaseio.com/',
    storageBucket: 'smarthomeautomation-3d999.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgD7L2p3y2bw9nvOj_H46X7EBJLZMw_lI',
    appId: '1:891579140465:web:dummy_web_app_id',
    messagingSenderId: '891579140465',
    projectId: 'smarthomeautomation-3d999',
    databaseURL: 'https://smarthomeautomation-3d999-default-rtdb.firebaseio.com/',
    storageBucket: 'smarthomeautomation-3d999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgD7L2p3y2bw9nvOj_H46X7EBJLZMw_lI',
    appId: '1:891579140465:web:dummy_web_app_id',
    messagingSenderId: '891579140465',
    projectId: 'smarthomeautomation-3d999',
    databaseURL: 'https://smarthomeautomation-3d999-default-rtdb.firebaseio.com/',
    storageBucket: 'smarthomeautomation-3d999.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgD7L2p3y2bw9nvOj_H46X7EBJLZMw_lI',
    appId: '1:891579140465:web:dummy_web_app_id',
    messagingSenderId: '891579140465',
    projectId: 'smarthomeautomation-3d999',
    databaseURL: 'https://smarthomeautomation-3d999-default-rtdb.firebaseio.com/',
    storageBucket: 'smarthomeautomation-3d999.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgD7L2p3y2bw9nvOj_H46X7EBJLZMw_lI',
    appId: '1:891579140465:web:dummy_web_app_id',
    messagingSenderId: '891579140465',
    projectId: 'smarthomeautomation-3d999',
    authDomain: 'smarthomeautomation-3d999.firebaseapp.com',
    databaseURL: 'https://smarthomeautomation-3d999-default-rtdb.firebaseio.com/',
    storageBucket: 'smarthomeautomation-3d999.appspot.com',
  );
}
